---
- name: create a network
  os_network:
       state: present
#       auth:
#          auth_url: "{{ auth_url_var }}"
#          auth_version: 3
#          user_domian_name: default
#          project_domain_name: default
#          username: "{{ username_var }}"
#          password: "{{ password_var }}"
#          project_name: "{{ project_name_var }}"
       endpoint_type: "{{ endpoint_type_var }}"
       name: "{{ item.network_name }}"
       shared: "{{ item.is_the_network_shared_between_customers }}"       
       external: "{{ item.accessable_outside_openstack_virtual_network }}"
       admin_state_up: True       
  register: justcreatednetwork
  with_items: "{{ networks_to_create }}"
  tags:
    - network
    - net-subnet
    

#aadl_route_dest: "130.1.1.0/24", addl_routing_gw: