---
- name: create a network
  os_network:
       state: present
       auth:
          auth_url: "{{ auth_url_var }}"
          auth_version: 3
          user_domian_name: default
          project_domain_name: default
          username: "{{ username_var }}"
          password: "{{ password_var }}"
          project_name: "{{ project_name_var }}"
       endpoint_type: "{{ endpoint_type_var }}"
       name: "{{ network_name }}"
       shared: "{{ is_the_network_shared_between_customers }}"       
       external: "{{ accessable_outside_openstack_virtual_network }}"
       admin_state_up: True       
  register: justcreatednetwork

