---
- hosts: localhost
  vars_files: 
    - define-deployment-variables.yml
    - opnstack_authfile.yml
  become: true
  roles:
    - { role: create-nova-vm, vnm: "{{ item.name }}", vimage: "{{ item.image }}", vkeyname: "{{ item.keyname }}", vflavor: "{{ item.flavor }}", vnetid: "{{ item.netid }}",
        vsecurity_group: "{{ item.security_group }}", vregister-OpenStack-VM: "{{ item.register-OpenStack-VM }}",
        vinmemory_inventory_group: "{{ item.inmemory_inventory_group }}" }
  with_items:
    - "{{ app-servers }}"
    - "{{ db-servers }}"
 

#- hosts: "{{ inmemory_inventory_group }}"
#  vars_files: define-deployment-variables.yml
#  remote_user: cloudy
#  become: true
#  roles:
#    - apply-common-config
#
#- hosts: new-openstack-servers
#  vars_files: define-deployment-variables.yml
#  remote_user: cloudy
#  become: true
#  roles:
#    - configure-db-mysql
#    - configure-webserver-apache
#  environment: "{{ proxy_env }}"
#
#- hosts: dcim
#  vars_files: define-deployment-variables.yml    
#  become: true
#  roles:
#    - configure-reverse-proxy
