---
- hosts: localhost
  vars_files: 
    - define-deployment-variables.yml
    - opnstack_authfile_wp.yml   
    
  roles:
    - create-network
    - create-subnetwork
    # - { role: create-internal-router, router_name: "{{routerNameA}}", subnet_names_tobeconnected: "{{subnetNamesTobeconnectedA}}" } 
    - { role: create-external-router, router_name: "{{routerNameB}}" ,
        external_network_attched_with_router: "{{externalNetworkAttchedWithRouterB}}" ,
         external_subnet_n_gatewayIP: "{{externalSubnetNgatewayIPB}}", 
         subnet_names_tobeconnected: "{{subnetNamesTobeconnectedB}}" }   
    - create-security-group
    - create-security-rules
    - create-nova-vm

- hosts: groupofjustcreatedvm
  vars_files: 
    - define-deployment-variables.yml
  remote_user: ubuntu
  become: true
  pre_tasks:
   - name: wait for python package installation by cloud init to be completed
     shell: /usr/bin/python --version
     register: result
     #until: result.stdout.find("not found") != -1
     until: result.rc == 0
     retries: 10
     delay: 30     
   - debug: var=result
     
  roles:
    - apply-common-config
    - { role: configure-db-mysql, when: "server_role == 'dbserver'" }
    - { role: configure-webserver-apache, when: "server_role == 'appserver'" }
  environment: "{{ proxy_env }}"
   
  tasks:
     - name: add the pre existing reverse proxy server name to inmemroy inventroy
       add_host: name=rpserver groups=groupofrpserver
            ansible_ssh_host={{reverseproxyserverip}}
            ansible_ssh_port={{reverseproxyserversshport}}
            hostname={{reverseproxyservername}}
   
- hosts: rpserver
  vars_files: 
    - define-deployment-variables.yml    
  remote_user: cloud
  become: true
 
