---
- hosts: localhost
  vars_files: 
    - define-deployment-variables.yml
    - opnstack_authfile.yml
  become: true
  roles: {{item}}
#    - { role: create-nova-vm, vnm: "{{ app_servers.name }}", vimage: "{{ app_servers.image }}", 
#        vkeyname: "{{ app_servers.keyname }}", vflavor: "{{ app_servers.flavor }}",
#         vnetid: "{{ app_servers.netid }}", vsecurity_group: "{{ app_servers.security_group }}", 
#         vregister-OpenStack-VM: "{{ app_servers.register-OpenStack-VM }}", 
#         vinmemory_inventory_group: "{{ app_servers.inmemory_inventory_group }}" }
#    - {{item}}
  with_items:
    - "{ role: create-nova-vm, vnm: {{ app_servers.name }}, vimage: {{ app_servers.image }}, 
        vkeyname: {{ app_servers.keyname }}, vflavor: {{ app_servers.flavor }},
         vnetid: {{ app_servers.netid }}, vsecurity_group: {{ app_servers.security_group }} }"  

- hosts: groupofjustcreatedvm
  vars_files: 
    - define-deployment-variables.yml
  remote_user: cloudy
  become: true
  roles:
    - apply-common-config
#
#- hosts: new-openstack-servers
#  vars_files: define-deployment-variables.yml
#  remote_user: cloudy
#  become: true
#  roles:
#    - configure-db-mysql
#    - configure-webserver-apache
#  environment: "{{ proxy_env }}"
#
#- hosts: dcim
#  vars_files: define-deployment-variables.yml    
#  become: true
#  roles:
#    - configure-reverse-proxy
