---
- hosts: localhost
  vars_files: 
    - define-deployment-variables.yml
    - opnstack_authfile_wp.yml
#  become: true 
   
  roles:
   
    - { role: create-nova-vm, vnm: "{{ db_servers.name }}", vimage: "{{ db_servers.image }}", 
        vkeyname: "{{ db_servers.keyname }}", vflavor: "{{ db_servers.flavor }}",
         vnetid: "{{ db_servers.netid }}", vfloating_ip_pool: "{{ db_servers.floating_ip_pool }}", 
         vsecurity_group: "{{ db_servers.security_group }}",  vservers_role: "{{ db_servers.server_role}}"  }
         
    - { role: create-nova-vm, vnm: "{{ app_servers.name }}", vimage: "{{ app_servers.image }}", 
        vkeyname: "{{ app_servers.keyname }}", vflavor: "{{ app_servers.flavor }}",
         vnetid: "{{ app_servers.netid }}", vfloating_ip_pool: "{{ app_servers.floating_ip_pool }}", 
         vsecurity_group: "{{ app_servers.security_group }}",vservers_role: "{{ app_servers.server_role}}"  }

#- hosts: groupofjustcreatedvm
#  vars_files:
#    - define-deployment-variables.yml
#  remote_user: ubuntu
#  become: true

  tasks:
    - debug:
         msg:  " {{ item }}  ansible_ssh_host={{ hostvars[item]['ansible_ssh_host'] }} "
         #msg:  " {{ hostvars[item]['ansible_hostname'] }}  {{ hostvars[item]['ansible_ssh_host'] }} "
         #msg:  " {{ item }} "
      with_items: "{{ groups['groupofjustcreatedvm'] }}"

    - name: creating an inventory file with the justcreated hostnames for later run
      template:
         src: e2d-inventory.j2
         dest: ./e2d-inventory.txt
                     

