---
- name: launch an nova instance 
  os_server: 
       state: present
       auth:
          auth_url: http://controller:35357/v2.0
          username: admin
          password: admin123
          project_name: admin
       name: "{{vnm}}"
       image: "{{vimage}}"
       key_name: "{{vkeynm}}"
       flavor: "{{vflavor}}"
       nics:
          - net-id: "{{vnetid}}"
#       auto_ip: yes
#       floating_ip_pools: ext-net
       security_groups: "{{vsecurity_group}}"
       config_drive: yes
#       meta:
#          hostname: vm4-auto-ubuntu
#          group: uge_master
       user_data: "{{ lookup('file', 'our-user-data-v3.txt') }}"
       timeout: 1500
#       wait: yes
  register: "{{register-OpenStack-VM}}"

- name: 'Waiting OS boot and SSH readiness'
  wait_for: 
       port: 22 
       #host: "{{ vnm }}"
       host: '{{"{{register-OpenStack-VM}}".server.public_v4}}'
       delay: 1
       timeout: 3000
  delay: 60
  retries: 30

- name: Add new  Instance  name to ansible  temporary in memroy  Inventory
  add_host: name={{vnm}} groups="{{inmemory-group-name}}"
            ansible_ssh_host='{{"{{register-OpenStack-VM}}".server.public_v4}}'

  
