---
# Create a new (or update an existing) subnet on the specified network
- name: Create a new (or update an existing) subnet on the specified network
  os_subnet:
    state: present
#    auth:
#          auth_url: "{{ auth_url_var }}"
#          username: "{{ username_var }}"
#          password: "{{ password_var }}"
#          project_name: "{{ project_name_var }}"
#          endpoint_type: "{{ endpoint_type_var }}"
    endpoint_type: "{{ endpoint_type_var }}"
    network_name: "{{ item.network_name }}"
    name: "{{ item.subnet_name }}"
    cidr: "{{ item.subnet_address_in_cidr }}"   
    dns_nameservers: "{{item.dns_server_for_subnet}}"       
    #host_routes: "{{item.additional_routing_for_subnet}}"
    enable_dhcp: "{{item.dhcp_to_be_enabled}}"
    allocation_pool_start: "{{item.dhcp_ip_allocation_pool_start}}"
    allocation_pool_end: "{{item.dhcp_ip_allocation_pool_end}}"
  register: justcreatedsubnetwork
  with_items: "{{ subnetworks_to_create }}"
  tags:
    - subnet
    - net-subnet