---
# Create a new (or update an existing) subnet on the specified network
- name: Create a new (or update an existing) subnet on the specified network
  os_subnet:
    state: present
    network_name: "{{ network_name }}"
    name: "{{ subnet_name }}"
    cidr: "{{ subnet_address_in_cidr }}"   
    dns_nameservers: "{{dns_server_for_subnet}}"       
    host_routes: "{{additional_routing_for_subnet}}"
    enable_dhcp: "{{dhcp_to_be_enabled}}"
    allocation_pool_start: "{{dhcp_ip_allocation_pool_start}}"
    allocation_pool_end: "{{dhcp_ip_allocation_pool_end}}"
  register: justcreatedsubnetwork
  