---
#- name: Create a router for tenant admin
#  quantum_router:
#       state: present
##       auth_url: "{{ auth_url_var }}"
##       login_username: "{{ username_var }}"
##       login_password: "{{ password_var }}"
##       login_tenant_name: "{{ project_name_var }}"
#       name: "{{router_name}}"
#- name: Link External Network
#  quantum_router_gateway:
#       state: present
#       auth_url: "{{ auth_url_var }}"
#       login_username: "{{ username_var }}"
#       login_password: "{{ password_var }}"
#       login_tenant_name: "{{ project_name_var }}"
#       router_name: "{{router_name}}"
#       network_name: "{{external_network_attched_with_router}}"
#       
#- name: attach private subnets
#  quantum_router_interface:
#       state: present
#       auth_url: "{{ auth_url_var }}"
#       login_username: "{{ username_var }}"
#       login_password: "{{ password_var }}"
#       login_tenant_name: "{{ project_name_var }}"
#       router_name: "{{router_name}}"
#       subnet_name: "{{subNetNameA}}"
#       
#- name: attach private subnets
#  quantum_router_interface:
#       state: present
#       auth_url: "{{ auth_url_var }}"
#       login_username: "{{ username_var }}"
#       login_password: "{{ password_var }}"
#       login_tenant_name: "{{ project_name_var }}"
#       router_name: "{{router_name}}"
#       subnet_name: "{{subNetNameB}}"
#   

## Create a new (or update an existing) subnet on the specified network
- name: Create a new (or update an existing) router to connect two subnets 
  os_router:
    state: present
#    auth:
#          auth_url: "{{ auth_url_var }}"
#          username: "{{ username_var }}"
#          password: "{{ password_var }}"
#          project_name: "{{ project_name_var }}"    
    endpoint_type: "{{ endpoint_type_var }}"
    name: "{{router_name}}"
    network: "{{external_network_attched_with_router}}"
##    external_fixed_ips: "{{external_subnet_n_gatewayIP}}" 
#    external_fixed_ips:  
#     - subnet: provider-303-subnet
#       ip: 191.1.1.15    
    interfaces: "{{subnet_names_tobeconnected}}"      
  
  