---
#- name: install mysql package
#  apt:
#    name: "{{ item }}"
#    state: present
#    allow_unauthenticated: yes
#  with_items: "{{db_server_apt_packages}}"   

- name: Configure my sql to listen and bind on all IP address 
  lineinfile:
   dest: /etc/mysql/my.cnf
   line: "bind-address    = 0.0.0.0"
   
   
- name: Start mysql server
  service: 
    name: mysql
    state: started

- name: Create database
  mysql_db:
    name: searchlog
    state: present


- name: Create user and give permissions
  mysql_user: name=mysql password=mysql123 host=localhost priv=*.*:ALL,GRANT state=absent
  
- name: Create user and give permissions
  mysql_user: name=mysql password=mysql123 host=% priv=*.*:ALL,GRANT state=present
  
- name: give permission to all hosts
  mysql_user: name=mysql  host_all=yes 

  
