---
- hosts: localhost
  become: true
  roles:
    - create-nova-vm
- hosts: new-openstack-servers
  remote_user: cloudy
  become: true
  roles:
    - apply-common-config
- hosts: new-openstack-servers
  remote_user: cloudy
  become: true
  roles:
    - configure-db-mysql
    - configure-webserver-apache
  environment: "{{ proxy_env }}"
- hosts: dcim
  vars_files: 
#    - 'roles/configure-reverse-proxy/vars/main.yml'
    - 'roles/create-nova-vm/vars/main.yml'
  become: true
  roles:
    - configure-reverse-proxy
