---
- name: Create security group
  os_security_group_rule: 
       state: present
#       auth:
#          auth_url: "{{ auth_url_var }}"
#          username: "{{ username_var }}"
#          password: "{{ password_var }}"
#          project_name: "{{ project_name_var }}"
       endpoint_type: "{{ endpoint_type_var }}"
       security_group: "{{item.secgroupName}}"
       protocol: "{{item.ruleprotocol}}"
       port_range_min: "{{item.startport}}"
       port_range_max: "{{item.endport}}"
       remote_ip_prefix: "{{item.ruleSourceIP}}"
  with_items: "{{ security_groups }}"
  tags:
     - sec-rule
     - security         

  