---
- name: Create security group
  os_security_group_rule: 
       state: present
#       auth:
#          auth_url: "{{ auth_url_var }}"
#          username: "{{ username_var }}"
#          password: "{{ password_var }}"
#          project_name: "{{ project_name_var }}"
       endpoint_type: "{{ endpoint_type_var }}"
       security_group: "{{secgroupName}}"
       protocol: "{{ruleprotocol}}"
       port_range_min: "{{startport}}"
       port_range_max: "{{endport}}"
       remote_ip_prefix: "{{ruleSourceIP}}"
        

  