---
- name: Create security group
  os_security_group:
       state: present
#       auth:
#          auth_url: "{{ auth_url_var }}"
#          username: "{{ username_var }}"
#          password: "{{ password_var }}"
#          project_name: "{{ project_name_var }}"
       endpoint_type: "{{ endpoint_type_var }}"
       name: "{{secgroupName}}"
        

  