---
- name: launch an nova instance 
  os_server: 
       state: present
#       auth:
#          auth_url: "{{ auth_url_var }}"
#          username: "{{ username_var }}"
#          password: "{{ password_var }}"
#          project_name: "{{ project_name_var }}"          
       endpoint_type: "{{ endpoint_type_var }}"
       name: "{{ item.vnm }}"
       image: "{{ item.vimage }}"
       key_name: "{{ item.vkeyname }}"
       flavor: "{{ item.vflavor }}"
       network: "{{ item.vnetid }}"
#       nics:
#          - net-id: "{{ vnetid }}"         
#       auto_ip: yes
       floating_ip_pools: "{{ item.vfloating_ip_pool }}"
       security_groups:
         - default
         - "{{ item.vsecurity_group }}"
       config_drive: yes
       #user_data: "{{ lookup('file', 'our-user-data-v3.txt') }}"
       user_data: |
        #cloud-config
        users: 
         - default
         - name: "{{ vinstance_login_name }}"
           homedir: "{{ vboot_login_home }}"
           shell: "{{ vboot_login_shell }}"
           ssh-authorized-keys: "{{ vboot_login_keys }}"
           sudo: "{{ vboot_login_sudo }}"
        manage_etc_hosts: true
        hostname: "{{ vnm }}"
        apt:
          conf: |
          proxy: "{{ vboot_apt_proxy }}"
          http_proxy: "{{ vboot_http_proxy }}"
          https_proxy: "{{ vobot_https_proxy }}"
        packages:
         - python         
       
       timeout: 1500
  register: justcreatedvm
  with_items: "{{ vms_to_create }}"
  tags:
   - create-nova-vm
   - vm

- name: 'Waiting OS boot and SSH readiness'
  wait_for: 
       port: 22        
       host: "{{ justcreatedvm.server.public_v4 }}"
       delay: 1
       timeout: 3000
  delay: 300 
  retries: 50
  tags:
   - vm
   - create-nova-vm

#in add host module dont quote  the variables , dont give space after equal to sign and no space before or after the 
#variable name inside curly braces  
- name: Add new  Instance  name to ansible  Inventory  
  add_host: name={{vnm}} groups=groupofjustcreatedvm
            ansible_ssh_host={{justcreatedvm.server.public_v4}}
            server_role={{vservers_role}}
  tags:
   - create-nova-vm
- name: pause for 5 minutes for cloud-init to complete python readiness
  pause: 
    minutes: 5
  tags:
   - vm
   - create-nova-vm
