---
# Create a new (or update an existing) subnet on the specified network
- name: Create a new (or update an existing) subnet on the specified network
  os_subnet:
    state: present
    auth:
          auth_url: "{{ auth_url_var }}"
          username: "{{ username_var }}"
          password: "{{ password_var }}"
          project_name: "{{ project_name_var }}"    
    name: "{{router_name}}"
    network: "{{external_network_attched_with_router}}"
    external_fixed_ips: "{{external_subnet_n_gatewayIP}}"      
    interfaces: "{{subnet_names_tobeconnected}}"      
  register: justcreatedrouter
  