---
# Create a new (or update an existing) subnet on the specified network
- name: Create a new (or update an existing) router to connect two subnets 
  os_router:
    state: present
    auth:
          auth_url: "{{ auth_url_var }}"
          username: "{{ username_var }}"
          password: "{{ password_var }}"
          project_name: "{{ project_name_var }}"    
    name: "{{router_name}}"        
    interfaces: "{{subnet_names_tobeconnected}}"      
  
  