host_table_entry: |
        10.0.0.100       dcim
etc_environment_entry: |
        export https_proxy="http://dcim:3128"
        export http_proxy="http://dcim:3128"
        no_proxy=localhost,127.0.0.1,10.*.*.*,*.poc,dcim,gitlab
apt_proxy_entry: |
        Acquire::http { Proxy "http://dcim:3128";};
        Acquire::https { Proxy "http://dcim:3128";};
